### ISSUE TITLE
x64 bit support

### ISSUE THREAD

**Issue by JCae2798** [Mpstark/articulate#87]
It's still in DEV branch, but hoping we can get support for x64 exe?  Thanks!

**Comment by SPARTAN563** [comment]
Sorry, took me a while to figure out that you were referring to the ArmA x64 execuable. I'll see if I can get my dev environment setup for this project again and add it (no promises on how long that could take, I haven't touched this codebase in months).

**Comment by JCae2798** [comment]
Much appreciated!  Sorry i wasn't clear about the app.

**Comment by SPARTAN563** [comment]
Just put out [v0.2.12](https://github.com/Mpstark/articulate/releases/tag/v0.2.12) - please let me know if you run into any issues with it. Unfortunately you will need to clear your config file for the changes to take effect 😞.

Bit of background on why the config clear is necessary, we had anticipated the need to add new executables down the line and made it configurable - however it wasn't a pressing concern when we were working on the project and so we never built a user interface for making those changes - the result is that the only way to change the list of executables is by loading an empty config file... Not the smartest approach, I know, and I do apologize for the inconvenience.

**Comment by JCae2798** [comment]
No need for apologies, much appreciated that you updated for the community!  

May i please ask what config file you are referring to?  Sorry if it's obvious, but check my user folder and app folder and could not find such file.

Thanks again.

**Comment by SPARTAN563** [comment]
No worries, in the release notes I've documented the steps you need to take to upgrade it (including where to find the file) - you can find the release notes [here](https://github.com/Mpstark/articulate/releases/tag/v0.2.12).

Let me know if it doesn't work for you.

**Comment by JCae2798** [comment]
Geez, can't believe i missed it.  Sorry once again.  Only note to add, is for me anyways, it was in the %AppData%\Roaming\Articulate folder.  

I cant tell ya right off the bat its working!  Will report back if i find any major bugs.  Thanks again man, really appreciate it!

**Comment by SPARTAN563** [comment]
Oh right, you're entirely correct - I'll fix that in the docs. 

It's a pleasure, enjoy
